## linear algebra
fecha: 30/12/2024
tema: algebra lineal, derivadas, funciones


In [43]:
import numpy as np
import matplotlib.pyplot as pit

In [44]:
vector1 = np.array([3, 4, 5]) #es un vector porque tiene solo 1 braket recto
vector1

array([3, 4, 5])

In [45]:
vector1.shape #Es un vector porque tiene la forma (numero de elementos, )

(3,)

In [46]:
vector1 + 1 #Broadcasting anade el 1 a cada elemento del vector

array([4, 5, 6])

In [47]:
vector1 * 0.5 #Numpy detecta el tipo de datos y convierte si fuera necesario

array([1.5, 2. , 2.5])

In [48]:
array1 = np.array([[3,1],[4,1],[1,1]])
array1

array([[3, 1],
       [4, 1],
       [1, 1]])

In [49]:
array1.shape #Esto es una matriz de 3 filas y 2 columnas

(3, 2)

In [50]:
vector2 = np.array([1,2,3])
vector3 = np.array([0,1,0.5])
vector2 * vector3 # Esta multiplicacion es elemento por elemento llamado producto Hadamard

array([0. , 2. , 1.5])

In [51]:
np.dot(vector2,vector3) #Este es el producto punto

np.float64(3.5)

In [52]:
array1 - 1

array([[2, 0],
       [3, 0],
       [0, 0]])

In [53]:
array2 = np.array([[1,2],[3,4]]) #las matrices con identica cantidad de filas y columnas se les llama matriz cuadrada
array3 = np.array([[1,0],[0,1]]) #las matrices cuya diagonal es uno y el resto 0 se les llama matriz identidad
array3

array([[1, 0],
       [0, 1]])

In [54]:
array2 + array3 #la suma de matrices esta permitida si tienen la misma cantidad de filas y columnas

array([[2, 2],
       [3, 5]])

In [55]:
array2 * array3 #Esta permitida si tiene la misma cantidad de filas y columnas

array([[1, 0],
       [0, 4]])

In [56]:
array4 = np.array([[0,1,2],[1,0,1]])
array4.shape

(2, 3)

In [57]:
array2.shape

(2, 2)

In [58]:
np.dot(array2,array4) #Array2 es 2x2 y array4 es 2x3 ademas la multiplicacion punto de matrices no es conmutativa a*b <> b*a

array([[ 2,  1,  4],
       [ 4,  3, 10]])

In [59]:
np.dot(array4,array2)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [33]:
print(f"{array2.shape} {array4.shape}")

(2, 2) (2, 3)


In [34]:
xvalues = np.linspace(-4,4) #linspace crea puntos equidistantes en un intervalo determinado
xvalues

array([-4.        , -3.83673469, -3.67346939, -3.51020408, -3.34693878,
       -3.18367347, -3.02040816, -2.85714286, -2.69387755, -2.53061224,
       -2.36734694, -2.20408163, -2.04081633, -1.87755102, -1.71428571,
       -1.55102041, -1.3877551 , -1.2244898 , -1.06122449, -0.89795918,
       -0.73469388, -0.57142857, -0.40816327, -0.24489796, -0.08163265,
        0.08163265,  0.24489796,  0.40816327,  0.57142857,  0.73469388,
        0.89795918,  1.06122449,  1.2244898 ,  1.3877551 ,  1.55102041,
        1.71428571,  1.87755102,  2.04081633,  2.20408163,  2.36734694,
        2.53061224,  2.69387755,  2.85714286,  3.02040816,  3.18367347,
        3.34693878,  3.51020408,  3.67346939,  3.83673469,  4.        ])

In [35]:
def square(x):
    return x * x

In [36]:
square(2)

4

In [38]:
f_xvalues = square(xvalues)
f_xvalues

array([1.60000000e+01, 1.47205331e+01, 1.34943773e+01, 1.23215327e+01,
       1.12019992e+01, 1.01357768e+01, 9.12286547e+00, 8.16326531e+00,
       7.25697626e+00, 6.40399833e+00, 5.60433153e+00, 4.85797584e+00,
       4.16493128e+00, 3.52519783e+00, 2.93877551e+00, 2.40566431e+00,
       1.92586422e+00, 1.49937526e+00, 1.12619742e+00, 8.06330696e-01,
       5.39775094e-01, 3.26530612e-01, 1.66597251e-01, 5.99750104e-02,
       6.66389005e-03, 6.66389005e-03, 5.99750104e-02, 1.66597251e-01,
       3.26530612e-01, 5.39775094e-01, 8.06330696e-01, 1.12619742e+00,
       1.49937526e+00, 1.92586422e+00, 2.40566431e+00, 2.93877551e+00,
       3.52519783e+00, 4.16493128e+00, 4.85797584e+00, 5.60433153e+00,
       6.40399833e+00, 7.25697626e+00, 8.16326531e+00, 9.12286547e+00,
       1.01357768e+01, 1.12019992e+01, 1.23215327e+01, 1.34943773e+01,
       1.47205331e+01, 1.60000000e+01])

In [66]:
plt.plot(xvalues,f_xvalues)
plt.show()

NameError: name 'plt' is not defined

In [62]:
def sinfuntion(x):
    return np.sin(x)

In [63]:
g_values = sinfuntion(xvalues)
plit.plot(xvalues,g_values)
plit.show()

NameError: name 'plit' is not defined

In [64]:
def two_the_power(x)
    return np.power(2,x)
h_values - two_the_power(xvalues)
plt.plot(xvalues,h_values)
plt.show


SyntaxError: expected ':' (2399969673.py, line 1)